import { useState } from 'react'
import { X, FileText } from 'lucide-react'

function RTIGenerator({ issue, onClose }) {
  const [copied, setCopied] = useState(false)

  const days = Math.floor(
    (Date.now() - new Date(issue.created_at)) / 86400000
  )

  const today = new Date().toLocaleDateString('en-IN', {
    day: 'numeric', month: 'long', year: 'numeric'
  })

  const reportDate = new Date(issue.created_at).toLocaleDateString('en-IN', {
    day: 'numeric', month: 'long', year: 'numeric'
  })

  const typeEmoji = (t) => {
    const map = {
      pothole: '🕳️', garbage: '🗑️', waterlogging: '🌊',
      streetlight: '💡', sewage: '🚰', tree: '🌳', other: '⚠️'
    }
    return map[t] || '⚠️'
  }

  const rtiText = `APPLICATION UNDER RIGHT TO INFORMATION ACT, 2005

Date: ${today}

To,
The Public Information Officer,
${issue.authority},
${issue.ward}

Subject: RTI Application regarding unresolved civic issue at ${issue.ward}

Sir/Madam,

Under the Right to Information Act, 2005, I hereby request the following information:

1. ISSUE DETAILS:
   - Type of Issue: ${issue.type?.toUpperCase()}
   - Location: ${issue.ward}
   - GPS Coordinates: ${issue.lat?.toFixed(4)}, ${issue.lng?.toFixed(4)}
   - Date First Reported: ${reportDate}
   - Days Unresolved: ${days} DAYS
   - Number of Citizens Reported: ${issue.report_count}
   - Current Status: ${issue.status?.toUpperCase()}

2. INFORMATION REQUESTED:

   a) What is the current status of the above mentioned 
      civic issue reported on ${reportDate}?

   b) What action has been taken by ${issue.authority} 
      to resolve this issue?

   c) Who is the designated officer responsible for 
      maintenance of ${issue.ward} area?

   d) What is the timeline for resolution of this issue?

   e) How many complaints were received regarding this 
      issue and what was the response to each?

   f) What is the budget allocated for maintenance of 
      civic infrastructure in ${issue.ward} for the 
      current financial year?

3. EVIDENCE:
   - This issue has been reported by ${issue.report_count} 
     citizens via FixMyCity platform
   - Issue has remained unresolved for ${days} days
   - GPS verified location: ${issue.lat?.toFixed(6)}, 
     ${issue.lng?.toFixed(6)}

I request the above information within 30 days as 
mandated by the RTI Act, 2005.

If the information is not provided within the stipulated 
time, I reserve the right to appeal to the First 
Appellate Authority.

Yours faithfully,

[Your Name]
[Your Address]
[Your Phone Number]
[Your Email]

---
Generated by FixMyCity — fixmycity-gamma.vercel.app
Empowering citizens. Demanding accountability.`

  const handleCopy = async () => {
    await navigator.clipboard.writeText(rtiText)
    setCopied(true)
    setTimeout(() => setCopied(false), 3000)
  }

  const handleWhatsAppShare = () => {
    const shortText = `📋 RTI APPLICATION FILED\n\nIssue: ${issue.type} at ${issue.ward}\nDays Ignored: ${days}\nAuthority: ${issue.authority}\nReports: ${issue.report_count} citizens\n\nFull RTI sent to ${issue.authority}.\n\n#RTI #FixMyCity #CivicRights`
    window.open(`https://wa.me/?text=${encodeURIComponent(shortText)}`, '_blank')
  }

  return (
    <div className="fixed inset-0 z-[100] bg-black/80 backdrop-blur-sm flex items-center justify-center p-4">
      <div className="w-full max-w-lg max-h-[90vh] flex flex-col">
        <div className="bg-[#0d1117] border border-blue-500/30 rounded-2xl overflow-hidden flex flex-col">
          <div className="bg-blue-900/50 border-b border-blue-500/20 px-5 py-4 flex items-center justify-between flex-shrink-0">
            <div className="flex items-center gap-3">
              <FileText size={20} className="text-blue-400" />
              <div>
                <p className="text-white font-bold">RTI Application</p>
                <p className="text-white/40 text-xs">Right to Information Act, 2005</p>
              </div>
            </div>
            <button onClick={onClose} className="text-white/30 hover:text-white">
              <X size={18} />
            </button>
          </div>

          <div className="px-5 py-3 bg-blue-500/5 border-b border-blue-500/10 flex-shrink-0">
            <div className="flex items-center gap-4">
              <span className="text-2xl">{typeEmoji(issue.type)}</span>
              <div className="flex-1">
                <p className="text-white font-semibold capitalize">{issue.type} — {issue.ward}</p>
                <p className="text-white/40 text-xs">{issue.report_count} reports · {days} days unresolved · {issue.authority}</p>
              </div>
              <div className="text-right">
                <p className="text-red-400 font-black text-2xl">{days}</p>
                <p className="text-red-400/60 text-[10px]">DAYS</p>
              </div>
            </div>
          </div>

          <div className="flex-1 overflow-y-auto p-5">
            <div className="bg-white/5 border border-white/10 rounded-xl p-4">
              <pre className="text-white/60 text-xs leading-relaxed whitespace-pre-wrap font-mono">
                {rtiText}
              </pre>
            </div>
          </div>

          <div className="px-5 py-4 border-t border-[#1e2433] space-y-2 flex-shrink-0">
            <p className="text-white/30 text-xs text-center mb-3">Copy this RTI and send to your local authority</p>

            <button
              onClick={handleCopy}
              className={`w-full font-semibold py-3 rounded-xl flex items-center justify-center gap-2 transition-all ${
                copied
                  ? 'bg-green-600 text-white'
                  : 'bg-blue-600 hover:bg-blue-700 text-white'
              }`}
            >
              {copied ? '✅ Copied!' : (
                <>
                  <FileText size={15} />
                  Copy RTI Application
                </>
              )}
            </button>

            <button
              onClick={handleWhatsAppShare}
              className="w-full bg-green-600 hover:bg-green-700 text-white font-semibold py-3 rounded-xl flex items-center justify-center gap-2 transition-all"
            >
              💬 Share RTI on WhatsApp
            </button>

            <div className="bg-yellow-500/10 border border-yellow-500/20 rounded-xl p-3">
              <p className="text-yellow-400 text-xs font-medium mb-1">📋 How to file this RTI:</p>
              <p className="text-white/40 text-xs">1. Copy the application above</p>
              <p className="text-white/40 text-xs">2. Send to your municipal authority office</p>
              <p className="text-white/40 text-xs">3. Or file online at rtionline.gov.in</p>
              <p className="text-white/40 text-xs">4. Authority must respond within 30 days</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

export default RTIGenerator
